-- BYTE BACK 방어전 2단계
-- 학습용 가상 메모 저장 테이블
-- 실제 학생 자료를 저장하지 않습니다.

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

-- 2단계에서는 auth.users와 외래키를 연결하지 않습니다.

alter table public.notes enable row level security;

-- anon / authenticated 역할에는 테이블 접근 권한을 부여하지 않습니다.
revoke all on table public.notes from anon, authenticated;

insert into public.notes (owner_id, title, content)
values
  (null, '과제', '실습용 가상 과제 기록'),
  (null, '포트폴리오', '실습용 가상 포트폴리오 기록'),
  (null, '아침 리추얼', '실습용 가상 리추얼 기록'),
  (null, '훈련 행정 자료', '실습용 가상 행정 기록');